name: CI

on:
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      # 使用別人寫好的安裝 Action
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      # 安裝 npm 套件
      - name: Install packages
        run: npm install
        
      # 建置專案並部署到 GitHub-pages，別人寫好的 yml
      - name: Build
        run: npm run build
      - name: Deploy to github-pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
